name: Generate Weekly Drift Graphic

on:
  schedule:
    - cron: '0 15 * * 2'
  workflow_dispatch:

jobs:
  build-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          pip install playwright
          playwright install chromium
          sudo npx playwright install-deps chromium

      - name: Run Script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python generate_graphic.py
